p = int(input("Enter the principal amount: "))  
r = int(input("Enter the rate of interest: "))
t = int(input("Enter the time period: "))
simple_interest = ((p * r * t)/100)
print(f"The simple interest is: {simple_interest} ")